<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>JeppIran.MSFSBridge</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.FlightSimulator.SimConnect">
      <HintPath>$(SIMCONNECT_MANAGED_DLL)</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
